numero = int(input('digite um numero: '))
print('='*18)
print(f'A tabuada de {numero} é: ')
print(f'1x{numero} = {numero*1}')
print(f'1x{numero} = {numero*2}')
print(f'1x{numero} = {numero*3}')
print(f'1x{numero} = {numero*4}')
print(f'1x{numero} = {numero*5}')
print(f'1x{numero} = {numero*6}')
print(f'1x{numero} = {numero*7}')
print(f'1x{numero} = {numero*8}')
print(f'1x{numero} = {numero*9}')
print(f'1x{numero} = {numero*10}')
print('='*18)
